### ISSUE TITLE
Not working §

### ISSUE THREAD

**Issue by baumars** [ozawa-hi/pdf2jrxml#1]
Hi,

Pb when running the jar : 

`> java -jar pdf2jrxml.jar -i sample.pdf -o sample.jrxml
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.remove(ArrayList.java:535)
        at com.hozawa.pdf2jrxml.JrxmlReport.createStaticText(JrxmlReport.java:193)
        at com.hozawa.pdf2jrxml.JrxmlReport.extractTextInPage(JrxmlReport.java:161)
        at com.hozawa.pdf2jrxml.JrxmlReport.extractElementsInPage(JrxmlReport.java:104)
        at com.hozawa.pdf2jrxml.JrxmlReport.generateJrxml(JrxmlReport.java:78)
        at com.hozawa.pdf2jrxml.JrxmlReport.generateJrxml(JrxmlReport.java:65)
        at com.hozawa.pdf2jrxml.Pdf2Jrxml.main(Pdf2Jrxml.java:92)
`

**Comment by ozawa-hi** [comment]
Thanks for reporting. Can you tell me which version of Java and the OS that you're running? I'll also appreciate if you can send me a sample pdf file that would cause this error. Thanks.

**Comment by baumars** [comment]
Hi, I am using AdoptOpnJDK 12 for Windows. The sample I used was the one you provided

**Comment by ozawa-hi** [comment]
Sorry, I haven't tested with JDK12 yet. I'm not sure if all the modules
including mine supports JDK12 yet. Will check with it.

**Comment by baumars** [comment]
Hi, are you sure it's working ? Because even when running with JDK 8, I still have the same error : 
`
java -jar pdf2jrxml-0.0.1-SNAPSHOT.jar -i sample.pdf -o teste.jrxml
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.remove(Unknown Source)
        at com.hozawa.pdf2jrxml.JrxmlReport.createStaticText(JrxmlReport.java:193)
        at com.hozawa.pdf2jrxml.JrxmlReport.extractTextInPage(JrxmlReport.java:161)
        at com.hozawa.pdf2jrxml.JrxmlReport.extractElementsInPage(JrxmlReport.java:104)
        at com.hozawa.pdf2jrxml.JrxmlReport.generateJrxml(JrxmlReport.java:78)
        at com.hozawa.pdf2jrxml.JrxmlReport.generateJrxml(JrxmlReport.java:65)
        at com.hozawa.pdf2jrxml.Pdf2Jrxml.main(Pdf2Jrxml.java:92)

 java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
`

**Comment by Sylvain-Assemat-DGC** [comment]
Missing lot of checkNull variable in code 
I can not have a valid result too even modifying code

**Comment by szjktms94** [comment]
@ozawa-hi I have the same issue.
I put this basic fix in the JrxmlReport.java createStatic function line 194:
			for (int i = 0; i < text.length(); i++) {
				if(charList.size() != 0) {
					charList.remove(0);
				}
			}
And now is executed properly but the result does not really look right with the basic sample you included.
