### ISSUE TITLE
Help to run project

### ISSUE THREAD

**Issue by alextgtome** [ozawa-hi/pdf2jrxml#2]
Hello, at first Thank's by project! That is a excelent idea.

I'm getting this error when I run the command ./pdf2jrxml.sh

`~/projetos/pdf2jrxml/target$ ./pdf2jrxml.sh
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.hozawa.pdf2jrxml.JrxmlReport.getFontName(JrxmlReport.java:448)
	at com.hozawa.pdf2jrxml.JrxmlReport.createStaticText(JrxmlReport.java:216)
	at com.hozawa.pdf2jrxml.JrxmlReport.extractTextInPage(JrxmlReport.java:161)
	at com.hozawa.pdf2jrxml.JrxmlReport.extractElementsInPage(JrxmlReport.java:104)
	at com.hozawa.pdf2jrxml.JrxmlReport.generateJrxml(JrxmlReport.java:78)
	at com.hozawa.pdf2jrxml.JrxmlReport.generateJrxml(JrxmlReport.java:65)
	at com.hozawa.pdf2jrxml.Pdf2Jrxml.main(Pdf2Jrxml.java:92)
`
Someone can help me?

**Comment by Sylvain-Assemat-DGC** [comment]
Maybe changing the JrxmlReport.java
Line 447 to ``` 	if (fontParts.length > 1) {	``` 	
or
Line 448 to  ``` fontName = fontParts[0]; ```
